@startuml
class CameraController {
    - _min : float = 0.0f
    - _max : float
    - Update() : void
    - OnDrawGizmos() : void
}
MonoBehaviour <|-- CameraController
CameraController --> "Target" PlayerController2D
@enduml
