@startuml
class GameOverMenu {
    + <<override>> OnNetworkSpawn() : void
    + ShowClientRpc() : void
    + RestartServerRpc() : void
    + MainMenuServerRpc() : void
}
NetworkBehaviour <|-- GameOverMenu
@enduml
