@startuml
class GameOverMenu {
    + <<override>> OnNetworkSpawn() : void
    + ShowClientRpc() : void
    + RestartServerRpc() : void
    + MainMenuServerRpc() : void
    - OnClientDisconnected(obj:ulong) : void
    - DisconnectClientsClientRpc() : void
}
NetworkBehaviour <|-- GameOverMenu
GameOverMenu --> "_menuPage" GameObject
GameOverMenu --> "_scoreText" Text
GameOverMenu --> "_menuButton" GameObject
GameOverMenu --> "_restartButton" GameObject
@enduml
