@startuml
class UsersAndScores {
    + UsersAndScores()
    + add(username:string, score:Score) : void
    + getUserScores(username:string) : List<Tuple<string, string>>
    + getAllScores() : List<Tuple<string, string>>
    + getAllScoresOrdered() : List<Tuple<string, string>>
}
class "List`1"<T> {
}
UsersAndScores o-> "_allUsersAndScores<Tuple<string, string>>" "List`1"
@enduml
